<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="thor_arm">

    <!-- Load Simulated or Real Hardware Interfaces -->
    <xacro:arg name="is_sim" default="true"/>

    <!-- Include Gazebo Parameters -->
    <xacro:include filename="$(find thor_urdf)/urdf/thor_gazebo.xacro" />

    <!-- Include ros2_control Plugins -->
    <xacro:include filename="$(find thor_urdf)/urdf/thor_arm.ros2_control.xacro" />

    <!-- Useful XACRO Variables (Properties) -->
    <xacro:property name="PI" value="3.14159265359" />
    <xacro:property name="effort" value="4.0" />
    <xacro:property name="velocity" value="1.0" />

    <!-- Useful Macros -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- Table Definition -->
    <link name="table">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="1.0 0.8 0.04"/> <!-- 1m x 0.8m x 4cm thick -->
            </geometry>
            <material name="wood">
                <color rgba="0.6 0.4 0.2 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="1.0 0.8 0.04"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10.0"/> <!-- 10kg table -->
    </link>

    <!-- Table Legs (4 legs) -->
    <xacro:property name="leg_radius" value="0.025"/>
    <xacro:property name="leg_height" value="0.7"/>
    <xacro:property name="table_top_z" value="0.72"/> <!-- Table top at 0.72m from ground -->

    <xacro:macro name="table_leg" params="x y">
        <link name="table_leg_${x}_${y}">
            <visual>
                <origin xyz="0 0 -${leg_height/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${leg_radius}" length="${leg_height}"/>
                </geometry>
                <material name="metal">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 -${leg_height/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${leg_radius}" length="${leg_height}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="1.0"/> <!-- 1kg per leg -->
        </link>

        <joint name="table_leg_${x}_${y}_joint" type="fixed">
            <parent link="table"/>
            <child link="table_leg_${x}_${y}"/>
            <origin xyz="${x} ${y} -0.02" rpy="0 0 0"/> <!-- 2cm below table top -->
        </joint>
    </xacro:macro>

    <!-- Create 4 legs at table corners -->
    <xacro:table_leg x="0.45" y="0.35"/>
    <xacro:table_leg x="0.45" y="-0.35"/>
    <xacro:table_leg x="-0.45" y="0.35"/>
    <xacro:table_leg x="-0.45" y="-0.35"/>

    <!-- Table Joint (connect to base_link or world) -->
    <joint name="table_joint" type="fixed">
        <parent link="base_link"/> <!-- or "world" if you want it fixed in the world -->
        <child link="table"/>
        <origin xyz="0.4 0.0 ${table_top_z}" rpy="0 0 0"/> <!-- Positioned in front of robot -->
    </joint>

    <!-- Gazebo properties for the table -->
    <gazebo reference="table">
        <material>Gazebo/Wood</material>
        <static>true</static> <!-- Table doesn't move -->
    </gazebo>

    <gazebo reference="table_leg_*">
        <material>Gazebo/Grey</material>
        <static>true</static>
    </gazebo>

</robot>