FILE: config/thor_controllers.yaml
================================================================================
thor_arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
      
    interface_name: position
    
    command_interfaces:
      - position
      
    state_interfaces:
      - position
      - velocity
      
    # Trajectory following parameters
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      base_joint:
        trajectory: 0.1
        goal: 0.05
      shoulder_joint:
        trajectory: 0.1
        goal: 0.05
      elbow_joint:
        trajectory: 0.1
        goal: 0.05
      wrist_pitch_joint:
        trajectory: 0.1
        goal: 0.05
      wrist_roll_joint:
        trajectory: 0.1
        goal: 0.05

thor_gripper_controller:
  ros__parameters:
    joint: gripper_joint
    
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 10.0
    
    # Gripper-specific parameters
    parallel_fingers: true

joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
      - gripper_joint
      
    interfaces:
      - position
      - velocity
      - effort
